In [50]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim

In [51]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [52]:
iris = load_iris()

In [53]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [54]:
x_train = torch.tensor(x_train, dtype=torch.float32)
x_test = torch.tensor(x_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)

In [55]:
class MLP(nn.Module):
  def __init__(self, inputSize):
    super().__init__()

    self.Model = nn.Sequential(

        nn.Linear(inputSize, 32),
        nn.ReLU(),

        nn.Linear(32, 64),
        nn.ReLU(),

        nn.Linear(64, 128),
        nn.ReLU(),

        nn.Linear(128, 3)
    )

  def forward(self, x):
    return self.Model(x)

In [56]:
mlp = MLP(x_train.shape[1]).to(device)

In [57]:
criteria = nn.CrossEntropyLoss()

In [58]:
MLPOptimizer = optim.Adam(mlp.parameters(), lr=0.001)

In [59]:
for epoch in range(500):

  prediction = mlp(x_train)
  loss = criteria(prediction, y_train)

  MLPOptimizer.zero_grad()
  loss.backward()
  MLPOptimizer.step()

  print(f"Epoch : {epoch+1}/500, Loss : {loss.item():.4}")

Epoch : 1/500, Loss : 1.117
Epoch : 2/500, Loss : 1.087
Epoch : 3/500, Loss : 1.065
Epoch : 4/500, Loss : 1.046
Epoch : 5/500, Loss : 1.031
Epoch : 6/500, Loss : 1.017
Epoch : 7/500, Loss : 1.004
Epoch : 8/500, Loss : 0.9898
Epoch : 9/500, Loss : 0.9753
Epoch : 10/500, Loss : 0.96
Epoch : 11/500, Loss : 0.944
Epoch : 12/500, Loss : 0.9272
Epoch : 13/500, Loss : 0.9097
Epoch : 14/500, Loss : 0.8913
Epoch : 15/500, Loss : 0.872
Epoch : 16/500, Loss : 0.8517
Epoch : 17/500, Loss : 0.8313
Epoch : 18/500, Loss : 0.8106
Epoch : 19/500, Loss : 0.7891
Epoch : 20/500, Loss : 0.7668
Epoch : 21/500, Loss : 0.7437
Epoch : 22/500, Loss : 0.7199
Epoch : 23/500, Loss : 0.6959
Epoch : 24/500, Loss : 0.6724
Epoch : 25/500, Loss : 0.6494
Epoch : 26/500, Loss : 0.6267
Epoch : 27/500, Loss : 0.6045
Epoch : 28/500, Loss : 0.583
Epoch : 29/500, Loss : 0.5625
Epoch : 30/500, Loss : 0.543
Epoch : 31/500, Loss : 0.5246
Epoch : 32/500, Loss : 0.5072
Epoch : 33/500, Loss : 0.4911
Epoch : 34/500, Loss : 0.4761
Ep

In [61]:
with torch.no_grad():
    outputs = mlp(x_test)
    _, predicted = torch.max(outputs, 1)

    accuracy = (predicted == y_test).float().mean()
    print("Accuracy:", accuracy.item())

Accuracy: 1.0


In [62]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, predicted))

[[10  0  0]
 [ 0 12  0]
 [ 0  0  8]]
