In [ ]:
import numpy as np
import pandas as pd
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import torch.nn as nn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch.optim as optim

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [ ]:
iris = load_iris()

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

In [ ]:
x_train = torch.tensor(x_train, dtype=torch.float32)
x_test = torch.tensor(x_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)

In [ ]:
class FCNN(nn.Module):
  def __init__(self,inputSize):
    super().__init__()

    self.Model = nn.Sequential(
        nn.Linear(inputSize, 32),
        nn.ReLU(),

        nn.Linear(32, 64),
        nn.ReLU(),

        nn.Linear(64, 128),
        nn.ReLU(),

        nn.Linear(128, 256),
        nn.ReLU(),

        nn.Linear(256, 3),
    )

  def forward(self,x):
    return self.Model(x)

In [ ]:
fcNN = FCNN(x_train.shape[1]).to(device)

In [ ]:
fcNNOptimizer= optim.Adam(fcNN.parameters(), lr=0.001)

In [ ]:
criterion = nn.CrossEntropyLoss()

In [ ]:
for epoch in range(100):
  output = fcNN(x_train)
  loss = criterion(output, y_train)

  fcNNOptimizer.zero_grad()
  loss.backward()
  fcNNOptimizer.step()

  print(f"epoch : {epoch+1}/100, Loss : {loss.item():.4}")

epoch : 1/100, Loss : 1.108
epoch : 2/100, Loss : 1.088
epoch : 3/100, Loss : 1.072
epoch : 4/100, Loss : 1.058
epoch : 5/100, Loss : 1.044
epoch : 6/100, Loss : 1.028
epoch : 7/100, Loss : 1.01
epoch : 8/100, Loss : 0.9894
epoch : 9/100, Loss : 0.9669
epoch : 10/100, Loss : 0.9423
epoch : 11/100, Loss : 0.9154
epoch : 12/100, Loss : 0.886
epoch : 13/100, Loss : 0.8542
epoch : 14/100, Loss : 0.8199
epoch : 15/100, Loss : 0.7835
epoch : 16/100, Loss : 0.7455
epoch : 17/100, Loss : 0.7063
epoch : 18/100, Loss : 0.6663
epoch : 19/100, Loss : 0.6265
epoch : 20/100, Loss : 0.5877
epoch : 21/100, Loss : 0.5507
epoch : 22/100, Loss : 0.5155
epoch : 23/100, Loss : 0.4827
epoch : 24/100, Loss : 0.4524
epoch : 25/100, Loss : 0.4243
epoch : 26/100, Loss : 0.398
epoch : 27/100, Loss : 0.3727
epoch : 28/100, Loss : 0.3484
epoch : 29/100, Loss : 0.3254
epoch : 30/100, Loss : 0.3036
epoch : 31/100, Loss : 0.2829
epoch : 32/100, Loss : 0.2628
epoch : 33/100, Loss : 0.243
epoch : 34/100, Loss : 0.2239


In [ ]:
with torch.no_grad():
    outputs = fcNN(x_test)
    _, predicted = torch.max(outputs, 1)

    accuracy = (predicted == y_test).float().mean()
    print("Accuracy:", accuracy.item())

Accuracy: 1.0


In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, predicted))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
